# Generated by Django 6.0.5 on 2026-06-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_noteversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='draft_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='draft_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
