# Generated by Django 6.0.5 on 2026-06-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_draft_content_note_draft_saved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='draft_content',
        ),
        migrations.RemoveField(
            model_name='note',
            name='draft_saved_at',
        ),
        migrations.AddField(
            model_name='noteversion',
            name='note_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
