# Generated by Django 6.0.5 on 2026-06-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_remove_note_draft_content_remove_note_draft_saved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='markdown_file',
            field=models.FileField(blank=True, null=True, upload_to='notes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='source_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
