# Generated by Django 6.0.5 on 2026-06-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_note_markdown_file_alter_note_source_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='markdown_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='rendered_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
